remote_theme: daviddarnes/alembic@main
plugins: 
 - jekyll-remote-theme

tittle: Shoe Type Recognizer
description: An Image classification API that can recognize shoe types between 36 types from any images of the shoe.

author:
  name: Md. Sanjid Hossain
  
